/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reviews` | `/reviews`; params?: Router.UnknownInputParams; } | { pathname: `/review/breakdown`; params?: Router.UnknownInputParams; } | { pathname: `/review/chat`; params?: Router.UnknownInputParams; } | { pathname: `/review/enhance`; params?: Router.UnknownInputParams; } | { pathname: `/review/networks`; params?: Router.UnknownInputParams; } | { pathname: `/review/photos`; params?: Router.UnknownInputParams; } | { pathname: `/review/rate`; params?: Router.UnknownInputParams; } | { pathname: `/review/recording`; params?: Router.UnknownInputParams; } | { pathname: `/review/result`; params?: Router.UnknownInputParams; } | { pathname: `/review/thankyou`; params?: Router.UnknownInputParams; } | { pathname: `/review/type`; params?: Router.UnknownInputParams; } | { pathname: `/review/voice`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reviews` | `/reviews`; params?: Router.UnknownOutputParams; } | { pathname: `/review/breakdown`; params?: Router.UnknownOutputParams; } | { pathname: `/review/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/review/enhance`; params?: Router.UnknownOutputParams; } | { pathname: `/review/networks`; params?: Router.UnknownOutputParams; } | { pathname: `/review/photos`; params?: Router.UnknownOutputParams; } | { pathname: `/review/rate`; params?: Router.UnknownOutputParams; } | { pathname: `/review/recording`; params?: Router.UnknownOutputParams; } | { pathname: `/review/result`; params?: Router.UnknownOutputParams; } | { pathname: `/review/thankyou`; params?: Router.UnknownOutputParams; } | { pathname: `/review/type`; params?: Router.UnknownOutputParams; } | { pathname: `/review/voice`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reviews${`?${string}` | `#${string}` | ''}` | `/reviews${`?${string}` | `#${string}` | ''}` | `/review/breakdown${`?${string}` | `#${string}` | ''}` | `/review/chat${`?${string}` | `#${string}` | ''}` | `/review/enhance${`?${string}` | `#${string}` | ''}` | `/review/networks${`?${string}` | `#${string}` | ''}` | `/review/photos${`?${string}` | `#${string}` | ''}` | `/review/rate${`?${string}` | `#${string}` | ''}` | `/review/recording${`?${string}` | `#${string}` | ''}` | `/review/result${`?${string}` | `#${string}` | ''}` | `/review/thankyou${`?${string}` | `#${string}` | ''}` | `/review/type${`?${string}` | `#${string}` | ''}` | `/review/voice${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reviews` | `/reviews`; params?: Router.UnknownInputParams; } | { pathname: `/review/breakdown`; params?: Router.UnknownInputParams; } | { pathname: `/review/chat`; params?: Router.UnknownInputParams; } | { pathname: `/review/enhance`; params?: Router.UnknownInputParams; } | { pathname: `/review/networks`; params?: Router.UnknownInputParams; } | { pathname: `/review/photos`; params?: Router.UnknownInputParams; } | { pathname: `/review/rate`; params?: Router.UnknownInputParams; } | { pathname: `/review/recording`; params?: Router.UnknownInputParams; } | { pathname: `/review/result`; params?: Router.UnknownInputParams; } | { pathname: `/review/thankyou`; params?: Router.UnknownInputParams; } | { pathname: `/review/type`; params?: Router.UnknownInputParams; } | { pathname: `/review/voice`; params?: Router.UnknownInputParams; };
    }
  }
}
